### ISSUE TITLE
Crash when chatting with Aide

### ISSUE THREAD

**Issue by ghostwriternr** [codestoryai/aide#968]
### Before submitting your bug report

- [X] I'm not able to find an [open issue](https://github.com/codestoryai/sidecar/issues) that reports the same bug

### Environment

```Markdown
- OS: Windows
- IDE version: 1.94.2.24317
```

### Description

When i try to chat o edit with aide
When send the menssage
And dont do a response

### Reproduction

![image](https://github.com/user-attachments/assets/54bf9941-5c66-47c0-8855-f9edb0fafe60)

### Log output

```Shell
Instance 1

2024-11-12 09:19:17.222 [error] TypeError: fetch failed
    at node:internal/deps/undici/undici:13178:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at t.SideCarClient.documentOpen (c:\Users\Nicolas\Downloads\Aide-win32-x64-1.94.2.24317\resources\app\extensions\codestory\dist\extension.js:2:910609)
    at c:\Users\Nicolas\Downloads\Aide-win32-x64-1.94.2.24317\resources\app\extensions\codestory\dist\extension.js:2:853001
```

Instance 2
```
2024-11-12 12:05:39.717 [error] TypeError: fetch failed
    at node:internal/deps/undici/undici:13178:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at t.SideCarClient.documentOpen (c:\Users\Nicolas\Downloads\Aide-win32-x64-1.94.2.24317\resources\app\extensions\codestory\dist\extension.js:2:910609)
    at c:\Users\Nicolas\Downloads\Aide-win32-x64-1.94.2.24317\resources\app\extensions\codestory\dist\extension.js:2:853001
```
```

**Comment by ghostwriternr** [comment]
This should be fixed on the latest build!
