### ISSUE TITLE
Assistent is not working, uncought error in "Running Extension"

### ISSUE THREAD

**Issue by LiviaH** [codestoryai/aide#993]
### Before submitting your bug report

- [X] I'm not able to find an [open issue](https://github.com/codestoryai/sidecar/issues) that reports the same bug

### Environment

```Markdown
Version: 1.94.2
Release: 24334
Commit: 467e3f07b2f457a84215e5d94f59f66de1c34612
Date: 2024-11-29T18:58:30.730Z
Electron: 30.5.0
ElectronBuildId: undefined
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Linux x64 5.4.0-198-generic
```

### Description

The assistant didn't work. I can send a prompt, but nothing happens. The "Running Extensions" view shows an uncaught error.  The error counter increases with each prompt.

### Reproduction

1. install AIDE
2. login to AIDE
3. send any prompt

### Log output

```Shell
2024-11-30 10:28:38.929 [info] Extension host with pid 3201481 started
2024-11-30 10:28:38.929 [info] Skipping acquiring lock for /home/XXX/.config/Aide/User/workspaceStorage/78a3a0c153f2db6229438ce90c956b8e.
2024-11-30 10:28:39.280 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2024-11-30 10:28:39.304 [info] ExtensionService#_doActivateExtension ms-python.python, startup: false, activationEvent: 'onLanguage:python', root cause: ms-python.debugpy
2024-11-30 10:28:39.635 [info] ExtensionService#_doActivateExtension codestory-ghost.codestoryai, startup: false, activationEvent: 'onAideAgent:aide'
2024-11-30 10:28:40.086 [info] ExtensionService#_doActivateExtension ms-python.debugpy, startup: false, activationEvent: 'onLanguage:python'
2024-11-30 10:28:40.217 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2024-11-30 10:28:40.303 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2024-11-30 10:28:40.422 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2024-11-30 10:28:50.186 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2024-11-30 10:28:50.188 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2024-11-30 10:30:23.480 [info] Eager extensions activated
2024-11-30 10:30:23.544 [info] ExtensionService#_doActivateExtension vscode.configuration-editing, startup: false, activationEvent: 'onLanguage:jsonc'
2024-11-30 10:30:23.558 [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2024-11-30 10:30:23.622 [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2024-11-30 10:31:30.913 [error] TypeError: fetch failed
	at node:internal/deps/undici/undici:13178:13
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async t.SideCarClient.documentOpen (/opt/aide/resources/app/extensions/codestory/dist/extension.js:2:910918)
	at async /opt/aide/resources/app/extensions/codestory/dist/extension.js:2:853300
2024-11-30 10:33:02.139 [error] TypeError: fetch failed
	at node:internal/deps/undici/undici:13178:13
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async t.callServerEventStreamingBufferedPOST (/opt/aide/resources/app/extensions/codestory/dist/extension.js:2:923299)
	at async t.SideCarClient.agentSessionChat (/opt/aide/resources/app/extensions/codestory/dist/extension.js:2:919419)
	at async t.AideAgentSessionProvider.reportAgentEventsToChat (/opt/aide/resources/app/extensions/codestory/dist/extension.js:2:789188)
	at async t.AideAgentSessionProvider.streamResponse (/opt/aide/resources/app/extensions/codestory/dist/extension.js:2:788425)
	at async t.AideAgentSessionProvider.processEvent (/opt/aide/resources/app/extensions/codestory/dist/extension.js:2:788141)
2024-11-30 10:45:51.190 [error] TypeError: fetch failed
	at node:internal/deps/undici/undici:13178:13
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async t.callServerEventStreamingBufferedPOST (/opt/aide/resources/app/extensions/codestory/dist/extension.js:2:923299)
	at async t.SideCarClient.agentSessionChat (/opt/aide/resources/app/extensions/codestory/dist/extension.js:2:919419)
	at async t.AideAgentSessionProvider.reportAgentEventsToChat (/opt/aide/resources/app/extensions/codestory/dist/extension.js:2:789188)
	at async t.AideAgentSessionProvider.streamResponse (/opt/aide/resources/app/extensions/codestory/dist/extension.js:2:788425)
	at async t.AideAgentSessionProvider.processEvent (/opt/aide/resources/app/extensions/codestory/dist/extension.js:2:788141)
```

**Comment by yxl23** [comment]
![image](https://github.com/user-attachments/assets/0c67e18d-dc0e-40bb-9253-20c88e357f67)
My assistant also doesn't work

**Comment by mford7998a** [comment]
im having the exact same problem

**Comment by bpawnzZ** [comment]
same here.. Just installed and mine doesn't work either
